### ISSUE TITLE
Convert Documenation to proper markdown for Assignment 1

### ISSUE THREAD

**Issue by hadron43** [hadron43/CSE231-OperatingSystems#1]
Doc Link for documentation:
https://docs.google.com/document/d/18jfW3JP2EUk1vWJvQuRq8ZmnsasaDtC93mI5UJ8o6Q8/edit?usp=sharing

Add two separate documentation files :
- [ ] Assignment1/1. Forking Exercise/README.md
- [ ] Assignment1/2. Custom Terminal/README.md

Apart from this, also attach screenshots for building and running.

**Comment by Prasuncypher** [comment]
Assign me

**Comment by cyberReckon** [comment]
Assign me

**Comment by hadron43** [comment]
First good PR will be merged.
